---
# Crash Course Python for Data Science - Intro to Pandas
---
# 04 - Cleaning Data
---

### Import pandas

In [0]:
# Run this!
import pandas as pd
print('pandas imported!')

### Import the data in the CSV file
You can find the data [here](https://raw.githubusercontent.com/axrd/datasets/master/gdpmessy2.csv). Should have a shape of (222,3). Use this [resource](https://www.iban.com/country-codes) to clean values correctly.

In [0]:
# Run this cell first to load the dataset.
df = pd.read_csv('https://raw.githubusercontent.com/axrd/datasets/master/gdpmessy2.csv', index_col=0)

### Quickly inspect the head

In [0]:

df.head()

### Inspect the tail

In [0]:
df.tail()

### What is the shape of the DataFrame? Does it correspond to what we expected?

In [0]:

df.shape

### Missing values?
Find all the missing values and correct them.

In [0]:
# First, check how many missing values you have 
# Hint: Use the sum() method

df.isnull().sum()

In [0]:
# Now, you need to know which are your missing values so that you can replace them. 
# Hint: Explore the different methods that pandas dataframes have to clean your dataset. 

df[df.isnull().any(axis=1)]

In [0]:
# Now that you know what is missing, you can 
# use this resource: https://www.iban.com/country-codes to clean the values correctly.

df.at[6, "countrys"] = "Anguilla"
df.at[14, "code"] = 'BHS'
df.at[16, "GDP"] = 186.6
df.at[20, "countrys"] = 'Belize'
df.at[55, "code"] = "DNK"
df.at[70, "GDP"] = 2902.0
df.at[90, 'code'] = 'HUN'
df.at[96, 'GDP'] = 245.8
df.at[100, 'code'] = 'JAM'
df.at[106, 'countrys'] = 'Kiribati'
df.at[200, 'code'] = 'TGO'
df.at[206, 'countrys'] = 'Tuvalu'

In [0]:
# Finally, check that everything worked and you don't have any 
# missing values anymore. 

df.isnull().sum()

### Find duplicate values  
Clean where necessary:  
*   France has a GDP of 2902.0 billion.
*   Ireland has a GDP of 245.80 billion.
*   Bangladesh has a GDP of 186.60 billion.

In [0]:
# Check if you have any duplicates for the variable "countrys"
# Hint: we did this in the workshop. Check your notes. 


df["countrys"].value_counts(sort=True).head()

In [0]:
# Check for duplicates in "GDP"

df["GDP"].value_counts(sort=True).head()

In [0]:
# Check for duplicates in "code"


df["code"].value_counts(sort=True).head()

In [0]:
# Solve any issues you found

df[df['code'] == "ARG"]
df.at[209, 'code'] = 'ARE'
df[df['code'] == "ZMB"]
df.at[221, 'code'] = 'ZWE'

### Verify the change persisted!

In [0]:
df["code"].value_counts(sort=True).head()

### You did it! This was quite a challenging exercise. Congratulations on your perseverance. See you on the next one.


---