---
# Crash Course Python for Data Science - Intro to Python  
---
# 06 - Numpy
---

### Import Numpy as Np

In [0]:
# Make sure you run this cell first
import numpy as np
print('NumPy imported!')

### Generate random numbers
Create a (5,3) Numpy array of random integer values between 0 and 100.

In [0]:
### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

x = np.random.randint(0,100, (5,3))
x

### Array practice

In [0]:
# Return the first row:

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Return the first row:
x[0,]

In [0]:
# Return last column

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Return last column
x[:, -1]

In [0]:
# Return the third column values from the 4th and 5th rows

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Return the third column values from the 4th and 5th rows
x[3:5,2]

In [0]:
# Multiply every value in the array by 2

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Multiply every value in the array by 2
x*2

In [0]:
# Divide every value by 3

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Divide every value by 3
x/3

In [0]:
# Increase the values in the first row by 12

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Increase the values in the first row by 12
x[0,] = x[0,] + 12
x

In [0]:
# Calculate the mean of the first column

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Calculate the mean of the first column
x[:,0].mean()

In [0]:
# Calculate the median of the array after removing the 2 smallest values in the array

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Calculate the median of the array after removing the 2 smallest values in the array
x1 = np.delete(x, x.argmin())
x1 = np.delete(x1, x1.argmin())
np.median(x1)

In [0]:
# Calculate the standard deviation of the first 3 rows

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Calculate the standard deviation of the first 3 rows
np.std(x[:3],)

In [0]:
# Return values in the second column greater than 25

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Return values in the second column greater than 25
print("Values bigger than 25 on the second column =", x[:,1][x[:,1]>25])

In [0]:
# Return values in the array under 40

### YOUR CODE GOES HERE ###

In [0]:
#@title Double click here for a sample solution

# Return values in the array under 40
print("Values under 40 in array =", x[x<40])